Repository jetstack/kube-oidc-proxy, pull requests merged in 2019-12, with the labels that each got.

#112 Add Service annotations to Helm Charts
  deploy/charts/kube-oidc-proxy/templates/service.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#100 In-cluster config only used when no client flags have been provided
  cmd/options/client.go
  cmd/run.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#110 Creates proper e2e testing suite
  .dockerignore
  Dockerfile
  Makefile
  cmd/app/options/client.go
  cmd/app/options/kube_oidc_proxy.go
  cmd/app/options/oidc.go
  cmd/app/options/plugin.go
  cmd/app/run.go
  cmd/main.go
  demo/yaml/kube-oidc-proxy.yaml
  deploy/charts/kube-oidc-proxy/templates/clusterrole.yaml
  go.mod
  go.sum
  pkg/e2e/e2e.go
  pkg/e2e/e2e_test.go
  pkg/e2e/issuer/issuer.go
  pkg/e2e/noimpersonation_test.go
  pkg/e2e/rbac_test.go
  pkg/e2e/token_passthrough_test.go
  pkg/e2e/token_test.go
  pkg/e2e/upgrade_test.go
  pkg/e2e/util_test.go
  test/e2e/framework/config/config.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/deploy.go
  test/e2e/framework/helper/helper.go
  test/e2e/framework/helper/kubectl.go
  test/e2e/framework/helper/pod.go
  test/e2e/framework/helper/requester.go
  test/e2e/framework/helper/secrets.go
  test/e2e/framework/helper/token.go
  test/e2e/framework/issuer/.gitignore
  test/e2e/framework/issuer/Dockerfile
  test/e2e/framework/issuer/cmd/main.go
  test/e2e/framework/issuer/cmd/options/options.go
  test/e2e/framework/issuer/pkg/issuer/issuer.go
  test/e2e/framework/util.go
  test/e2e/suite/cases/doc.go
  test/e2e/suite/cases/impersonation/impersonation.go
  test/e2e/suite/cases/passthrough/passthrough.go
  test/e2e/suite/cases/rbac/rbac.go
  test/e2e/suite/cases/token/token.go
  test/e2e/suite/cases/upgrade/upgrade.go
  test/e2e/suite/suite.go
  test/e2e/suite/suite_test.go
  test/e2e/util/util.go
  test/environment/dev/dev.go
  test/environment/environment.go
  test/kind/image.go
  test/kind/kind.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL
