Repository jetstack/kube-oidc-proxy, pull requests merged in 2019-11, with the labels that each got.

#106 Move ca files into own modules
  demo/infrastructure/amazon/dns.tf
  demo/infrastructure/amazon/outputs.tf
  demo/infrastructure/amazon/providers.tf
  demo/infrastructure/digitalocean/dns.tf
  demo/infrastructure/digitalocean/outputs.tf
  demo/infrastructure/digitalocean/providers.tf
  demo/infrastructure/google/dns.tf
  demo/infrastructure/google/output.tf
  demo/infrastructure/modules/ca/ca.tf
  demo/infrastructure/modules/google-dns/dns.tf
  demo/manifests/main.jsonnet
Labels: approved, dco-signoff: yes, lgtm, size/L

#101 Upgrade go-lint to 1.18
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#111 Upgrade golangci-lint
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S
