Repository jetstack/kube-oidc-proxy, pull requests merged in 2019-05, with the labels that each got.

#60 Fix some typos in the README
  demo/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#61 Add return to Error switch case
  pkg/proxy/proxy.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#58 Use sha hash of demo in it's file url for versioning
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#57 Update diagram to avoid confusion and store image in cloud
  README.md
  img/kube-oidc-proxy.png
  img/kube-oidc-proxy.xml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#66 Make kube-oidc-proxy's image configurable
  demo/manifests/components/kube-oidc-proxy.jsonnet
Labels: approved, dco-signoff: yes, lgtm, size/XS

#64 Add digitalocean and simplify manifest generation
  demo/Makefile
  demo/README.md
  demo/config.dist.jsonnet
  demo/infrastructure/digitalocean/.gitignore
  demo/infrastructure/digitalocean/dns.tf
  demo/infrastructure/digitalocean/outputs.tf
  demo/infrastructure/digitalocean/providers.tf
  demo/infrastructure/digitalocean/secrets.tf
  demo/infrastructure/digitalocean/suffix.tf
  demo/infrastructure/modules/digitalocean-cluster/cluster.tf
  demo/infrastructure/modules/digitalocean-cluster/outputs.tf
  demo/manifests/components/contour.jsonnet
  demo/manifests/components/dex.jsonnet
  demo/manifests/components/gangway.jsonnet
  demo/manifests/components/kube-oidc-proxy.jsonnet
  demo/manifests/main.jsonnet
  demo/manifests/vendor/kube-prod-runtime/components/externaldns.jsonnet
Labels: approved, dco-signoff: yes, lgtm, size/XL

#65 Ensure authenticated group is added
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#68 Adds nginx config edit to increase max url size
  demo/manifests/components/landingpage.jsonnet
Labels: approved, dco-signoff: yes, size/M

#67 Add landing page
  demo/manifests/components/landingpage.jsonnet
  demo/manifests/components/landingpage/amazon.svg
  demo/manifests/components/landingpage/digitalocean.svg
  demo/manifests/components/landingpage/google.svg
  demo/manifests/components/landingpage/index.html
  demo/manifests/main.jsonnet
Labels: approved, dco-signoff: yes, lgtm, size/L
