Repository jetstack/kube-oidc-proxy, pull requests merged in 2019-09, with the labels that each got.

#79 Adds check-pick file to automate generating cherry pick PRs
  hack/cherry-pick-pull.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#59 Enable custom CA certificates for kube-oidc-proxy tutorial
  demo/Makefile
  demo/README.md
  demo/infrastructure/google/dns.tf
  demo/infrastructure/google/providers.tf
  demo/infrastructure/modules/google-dns/dns.tf
  demo/manifests/components/cert-manager.jsonnet
  demo/manifests/main.jsonnet
Labels: approved, dco-signoff: yes, lgtm, size/L

#95 Use `httpGet` readiness probe for proxy Pod
  demo/manifests/components/kube-oidc-proxy.jsonnet
  demo/yaml/kube-oidc-proxy.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#97 Add helm chart
  README.md
  deploy/charts/kube-oidc-proxy/.helmignore
  deploy/charts/kube-oidc-proxy/Chart.yaml
  deploy/charts/kube-oidc-proxy/README.md
  deploy/charts/kube-oidc-proxy/templates/NOTES.txt
  deploy/charts/kube-oidc-proxy/templates/_helpers.tpl
  deploy/charts/kube-oidc-proxy/templates/clusterrole.yaml
  deploy/charts/kube-oidc-proxy/templates/clusterrolebinding.yaml
  deploy/charts/kube-oidc-proxy/templates/deployment.yaml
  deploy/charts/kube-oidc-proxy/templates/ingress.yaml
  deploy/charts/kube-oidc-proxy/templates/secret_config.yaml
  deploy/charts/kube-oidc-proxy/templates/secret_tls.yaml
  deploy/charts/kube-oidc-proxy/templates/service.yaml
  deploy/charts/kube-oidc-proxy/templates/serviceaccount.yaml
  deploy/charts/kube-oidc-proxy/templates/tests/test-connection.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XL

#98 Fix a couple bugs in the helm chart
  deploy/charts/kube-oidc-proxy/templates/secret_config.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#96 Upgrade kind to 0.5.1
  go.mod
  go.sum
  pkg/e2e/e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M
