Repository jetstack/kube-oidc-proxy, pull requests merged in 2020-01, with the labels that each got.

#115 Makes readiness probe rely on proxy initialization on issuer
  cmd/app/options/kube_oidc_proxy.go
  cmd/app/run.go
  pkg/probe/probe.go
  pkg/probe/probe_test.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/util/token.go
  test/e2e/framework/helper/deploy.go
  test/e2e/suite/cases/doc.go
  test/e2e/suite/cases/probe/probe.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#113 Add junit test reports
  .gitignore
  Makefile
  go.mod
  go.sum
  test/e2e/suite/suite_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#118 Update demo components
  demo/Makefile
  demo/infrastructure/digitalocean/providers.tf
  demo/infrastructure/modules/amazon-cluster/cluster.tf
  demo/manifests/components/cert-manager.jsonnet
  demo/manifests/components/cert-manager/cert-manager.json
  demo/manifests/components/kube-oidc-proxy.jsonnet
  demo/manifests/main.jsonnet
  hack/boilerplate/boilerplate.py
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#119 Fix automated deployment of DNS service acccount
  demo/manifests/main.jsonnet
Labels: approved, dco-signoff: yes, lgtm, size/S

#120 Remove overwrite of certificate CRD object
  demo/manifests/components/cert-manager.jsonnet
Labels: approved, dco-signoff: yes, lgtm, size/S

#117 Update image tags to v0.2.0
  demo/manifests/components/kube-oidc-proxy.jsonnet
  demo/yaml/kube-oidc-proxy.yaml
  deploy/charts/kube-oidc-proxy/Chart.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#107 Move static manifests from demo to deploy
  README.md
  deploy/charts/kube-oidc-proxy/README.md
  deploy/yaml/kube-oidc-proxy.yaml
  deploy/yaml/secrets.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
