Repository jetstack/kube-oidc-proxy, pull requests merged in 2020-02, with the labels that each got.

#126 Add Pod Disruption Budget to Helm Charts
  deploy/charts/kube-oidc-proxy/templates/poddisruptionbudget.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#127 Handle makefile errors in piped commands
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#124 Upgrade k8s dependancies
  go.mod
  go.sum
  pkg/proxy/tokenreview/fake/tokenreview.go
  test/environment/dev/dev.go
  test/environment/environment.go
  test/kind/image.go
  test/kind/kind.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#128 Extra User Info Impersonation Headers
  Makefile
  README.md
  cmd/app/options/kube_oidc_proxy.go
  cmd/app/run.go
  deploy/charts/kube-oidc-proxy/templates/_helpers.tpl
  deploy/charts/kube-oidc-proxy/templates/deployment.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
  docs/tasks/extra-impersonation-headers.md
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/util/flags/string_to_string_slice.go
  pkg/util/flags/string_to_string_slice_test.go
  test/e2e/framework/fake-apiserver/.gitignore
  test/e2e/framework/fake-apiserver/Dockerfile
  test/e2e/framework/fake-apiserver/cmd/main.go
  test/e2e/framework/fake-apiserver/cmd/options/options.go
  test/e2e/framework/fake-apiserver/pkg/server/server.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/deploy.go
  test/e2e/framework/helper/requester.go
  test/e2e/framework/helper/token.go
  test/e2e/framework/issuer/pkg/issuer/issuer.go
  test/e2e/suite/cases/doc.go
  test/e2e/suite/cases/headers/headers.go
  test/e2e/suite/cases/impersonation/impersonation.go
  test/e2e/suite/cases/passthrough/passthrough.go
  test/e2e/suite/cases/probe/probe.go
  test/e2e/suite/cases/token/token.go
  test/e2e/suite/cases/upgrade/upgrade.go
  test/environment/environment.go
  test/kind/image.go
  test/kind/kind.go
  test/util/strings.go
  test/util/tls.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#129 Cleans up command options package
  cmd/app/options/app.go
  cmd/app/options/audit.go
  cmd/app/options/client.go
  cmd/app/options/misc.go
  cmd/app/options/oidc.go
  cmd/app/options/options.go
  cmd/app/options/serving.go
  cmd/app/run.go
  hack/lib/version.sh
  pkg/version/version.go
Labels: approved, dco-signoff: yes, lgtm, size/L
