Repository jetstack/kube-oidc-proxy, pull requests merged in 2020-03, with the labels that each got.

#121 Failure to provision managed worker nodes as call to kubernetes provider fails to find current kubeconfig
  demo/infrastructure/modules/amazon-cluster/cluster.tf
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#137 Adds --flush-interval to set the flush interval of proxy handler
  cmd/app/options/app.go
  cmd/app/run.go
  pkg/proxy/proxy.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#133 Dev cluster deploy improvments
  .dockerignore
  Dockerfile
  Makefile
  README.md
  docs/tasks/development-testing.md
  test/e2e/framework/helper/deploy.go
  test/e2e/suite/cases/headers/headers.go
  test/e2e/suite/suite.go
  test/environment/dev/dev.go
  test/environment/environment.go
  test/kind/image.go
  test/kind/kind.go
  test/tools/fake-apiserver/.gitignore
  test/tools/fake-apiserver/Dockerfile
  test/tools/fake-apiserver/cmd/main.go
  test/tools/fake-apiserver/cmd/options/options.go
  test/tools/fake-apiserver/pkg/server/server.go
  test/tools/issuer/.gitignore
  test/tools/issuer/Dockerfile
  test/tools/issuer/cmd/main.go
  test/tools/issuer/cmd/options/options.go
  test/tools/issuer/pkg/issuer/issuer.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#136 Handler based chaining for proxy
  Makefile
  cmd/app/options/options.go
  cmd/app/run.go
  pkg/proxy/context/context.go
  pkg/proxy/handlers.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  test/e2e/framework/framework.go
  test/e2e/suite/cases/impersonation/impersonation.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#134 Set client IP as x-forwarded value is available.
  docs/tasks/extra-impersonation-headers.md
  go.mod
  go.sum
  pkg/proxy/context/context.go
  pkg/proxy/handlers.go
  pkg/proxy/proxy.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#138 Auditing
  Dockerfile
  README.md
  cmd/app/options/options.go
  cmd/app/run.go
  deploy/charts/kube-oidc-proxy/templates/deployment.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
  docs/tasks/auditing.md
  pkg/proxy/audit/audit.go
  pkg/proxy/audit/handler.go
  pkg/proxy/handlers.go
  pkg/proxy/hooks/hooks.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/deploy.go
  test/e2e/framework/helper/kubectl.go
  test/e2e/suite/cases/audit/audit.go
  test/e2e/suite/cases/doc.go
  test/e2e/suite/cases/probe/probe.go
  test/e2e/suite/cases/upgrade/upgrade.go
  test/kind/image.go
  test/tools/audit-webhook/.gitignore
  test/tools/audit-webhook/Dockerfile
  test/tools/audit-webhook/cmd/main.go
  test/tools/audit-webhook/cmd/options/options.go
  test/tools/audit-webhook/pkg/sink/sink.go
  test/tools/fake-apiserver/Dockerfile
  test/tools/issuer/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XL

#144 Updates helm chart for service options …
  deploy/charts/kube-oidc-proxy/templates/service.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/S

#145 Updates image tags to v0.3.0
  demo/manifests/components/kube-oidc-proxy.jsonnet
  deploy/charts/kube-oidc-proxy/Chart.yaml
  deploy/charts/kube-oidc-proxy/values.yaml
  deploy/yaml/kube-oidc-proxy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
